---
- hosts: all
  become: yes
  vars:
   username: vagrant

  tasks:
  - name: Install zsh cause it's the bestest and some other stuff
    apt:
      pkg:
        - zsh
        - git

  - name: Do a curl thing to install antigen
    get_url:
      url: 'https://git.io/antigen' 
      dest: '/home/{{ username }}/antigen.zsh'
      mode: '0766'
      owner: '{{ username }}'
      group: '{{ username }}'

  - name: Ansible create file if it doesn't exist example
    file:
      path: '/home/{{ username }}/.zshrc'
      state: touch
      owner: '{{ username }}'
      group: '{{ username }}'
      
  - name: Edit zsh start to use powerlevel10k
    copy:
      dest: '/home/{{ username }}/.zshrc'
      content: |
        source /home/{{ username }}/antigen.zsh
        antigen use oh-my-zsh
        antigen theme romkatv/powerlevel10k
        antigen apply

  - name: We really should use zsh since we are setting it up
    user:
      name: '{{ username }}'
      shell: /bin/zsh
